name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    paths:
      - "RusArtWikimedia.zip"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Unzip project
        run: |
          set -e
          rm -rf project
          mkdir -p project
          unzip -o RusArtWikimedia.zip -d project
          echo "Unzipped"

      - name: Generate Gradle wrapper
        working-directory: project
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gradle
          gradle wrapper --gradle-version 8.7
          chmod +x ./gradlew

      - name: Build debug APK
        working-directory: project
        run: |
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RusArtWidget-debug
          path: project/app/build/outputs/apk/debug/*.apk
